"""initial schema

Revision ID: 3c61aedc90c5
Revises: 
Create Date: 2026-09-26 10:59:02.104312
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '3c61aedc90c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('external_model_id', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models')),
    sa.UniqueConstraint('provider', 'model_name', 'role', name=op.f('uq_models_provider'))
    )
    op.create_table('projects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('external_project_id', sa.String(length=100), nullable=True),
    sa.Column('repository_path', sa.String(length=1024), nullable=False),
    sa.Column('default_branch', sa.String(length=200), nullable=False),
    sa.Column('worker_profile', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('protected_paths', sa.JSON(), nullable=False),
    sa.Column('milestone_interval', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('external_project_id', name=op.f('uq_projects_external_project_id'))
    )
    op.create_table('milestones',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('after_task_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('starting_commit', sa.String(length=64), nullable=True),
    sa.Column('ending_commit', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_milestones_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestones'))
    )
    op.create_table('tasks',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('external_task_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('section', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('complexity', sa.String(length=16), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('depends_on', sa.JSON(), nullable=False),
    sa.Column('verify_commands', sa.JSON(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('max_review_cycles', sa.Integer(), nullable=False),
    sa.Column('max_runtime_minutes', sa.Integer(), nullable=False),
    sa.Column('max_files_changed', sa.Integer(), nullable=False),
    sa.Column('max_diff_lines', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_tasks_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks')),
    sa.UniqueConstraint('project_id', 'external_task_id', name=op.f('uq_tasks_project_id'))
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('ix_tasks_project_status', ['project_id', 'status'], unique=False)

    op.create_table('task_runs',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('review_cycle', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('external_run_id', sa.String(length=64), nullable=True),
    sa.Column('coder_model_id', sa.Uuid(), nullable=True),
    sa.Column('worker_image', sa.String(length=300), nullable=True),
    sa.Column('starting_commit', sa.String(length=64), nullable=True),
    sa.Column('candidate_commit', sa.String(length=64), nullable=True),
    sa.Column('branch_name', sa.String(length=300), nullable=True),
    sa.Column('context_hash', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('failure_reason', sa.String(length=50), nullable=True),
    sa.Column('artifact_path', sa.String(length=1024), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['coder_model_id'], ['models.id'], name=op.f('fk_task_runs_coder_model_id_models'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_runs_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_runs')),
    sa.UniqueConstraint('external_run_id', name=op.f('uq_task_runs_external_run_id')),
    sa.UniqueConstraint('task_id', 'run_number', name=op.f('uq_task_runs_task_id'))
    )
    with op.batch_alter_table('task_runs', schema=None) as batch_op:
        batch_op.create_index('ix_task_runs_status', ['status'], unique=False)

    op.create_table('artifacts',
    sa.Column('task_run_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_runs.id'], name=op.f('fk_artifacts_task_run_id_task_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts'))
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index('ix_artifacts_run_kind', ['task_run_id', 'kind'], unique=False)

    op.create_table('human_escalations',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('task_run_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_human_escalations_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_runs.id'], name=op.f('fk_human_escalations_task_run_id_task_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_human_escalations'))
    )
    op.create_table('model_runs',
    sa.Column('task_run_id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_artifact', sa.String(length=1024), nullable=True),
    sa.Column('response_artifact', sa.String(length=1024), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_model_runs_model_id_models'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_runs.id'], name=op.f('fk_model_runs_task_run_id_task_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_runs'))
    )
    op.create_table('reviews',
    sa.Column('task_run_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_provider', sa.String(length=100), nullable=False),
    sa.Column('reviewer_model', sa.String(length=200), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('risk', sa.String(length=16), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_reviews_confidence_range')),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_runs.id'], name=op.f('fk_reviews_task_run_id_task_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    op.create_table('run_events',
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('task_run_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('model_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_run_events_model_id_models'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_run_events_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_run_events_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_runs.id'], name=op.f('fk_run_events_task_run_id_task_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_events'))
    )
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.create_index('ix_run_events_run_sequence', ['task_run_id', 'sequence'], unique=False)

    op.create_table('verification_runs',
    sa.Column('task_run_id', sa.Uuid(), nullable=False),
    sa.Column('verification_type', sa.String(length=32), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('stdout_artifact', sa.String(length=1024), nullable=True),
    sa.Column('stderr_artifact', sa.String(length=1024), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_runs.id'], name=op.f('fk_verification_runs_task_run_id_task_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_runs'))
    )
    op.create_table('review_issues',
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('file', sa.String(length=1024), nullable=True),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('requirement_id', sa.String(length=100), nullable=True),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('required_fix', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_review_issues_review_id_reviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_issues'))
    )
    op.create_table('lessons',
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('framework', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('lesson', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('source_review_issue_id', sa.Uuid(), nullable=True),
    sa.Column('source_task_id', sa.Uuid(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('times_retrieved', sa.Integer(), nullable=False),
    sa.Column('times_applied', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_lessons_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_review_issue_id'], ['review_issues.id'], name=op.f('fk_lessons_source_review_issue_id_review_issues'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_task_id'], ['tasks.id'], name=op.f('fk_lessons_source_task_id_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lessons'))
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index('ix_lessons_retrieval', ['language', 'framework', 'category'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index('ix_lessons_retrieval')

    op.drop_table('lessons')
    op.drop_table('review_issues')
    op.drop_table('verification_runs')
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.drop_index('ix_run_events_run_sequence')

    op.drop_table('run_events')
    op.drop_table('reviews')
    op.drop_table('model_runs')
    op.drop_table('human_escalations')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index('ix_artifacts_run_kind')

    op.drop_table('artifacts')
    with op.batch_alter_table('task_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_task_runs_status')

    op.drop_table('task_runs')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_project_status')

    op.drop_table('tasks')
    op.drop_table('milestones')
    op.drop_table('projects')
    op.drop_table('models')
    # ### end Alembic commands ###
